### PR TITLE
Bump package versions and enhance kbar

### PR DESCRIPTION
**Pull request by timlrx**
## Change Log
- Bump next.js to 13.4.19
- Bump pliny to 0.1.2 which exposes more customization options for kbar
- Add FAQ section to readme

### CODE REVIEW

**Comment by techroider** [comment]
image

The kbar bug still exists. I don't know what to do

**Comment by techroider** [comment]
I just wrote "안녕하세요".

**Comment by timlrx** [comment]
> image
> 
> The kbar bug still exists. I don't know what to do

Yes it still exists. From the discussions, it seem like a kbar search issue with react 18. Hopefully, it would be patch soon and I will update it.

**Comment by techroider** [comment]
Thank you so much for your care 😍

**Comment by BennyDanielT** [comment]
Hey! Any updates on how one can resolve this issue?

**Pull request merged**
