### PR TITLE
chore: cleanup and fixes

### PR DESCRIPTION
**Pull request by Kosai106**
- Switched to Yarn over NPM
- Updates dependencies to `next@13`
- Removes `style` tags in favour of Tailwind arbitrary values
- Removes the need for `<a>` tags inside of `<Link>`
- Removes `<button>` nested inside of `<Link>` (This is a no no ♿️)
- Removes `role="button"` when not needed (Buttons inherently have this role already)
- Nest `<input>` inside of `<label>` elements ♿️
- Generally remove unnecessary code
... And more

### CODE REVIEW

**Comment by Kosai106** [comment]
Okay, so this PR was supposed to be opened for my local branch... But feel free to have a look and consider my changes here too I suppose. 🤷‍♂️

**Comment by timlrx** [comment]
Thanks, very nice. I was planning to update the successor of this project (Pliny) to nextjs 13 so this comes in very handy! I won't merge the PR. I will just make the changes to the other repo before copying back to this repo as v2...sometime soon.

**Comment by Kosai106** [comment]
@timlrx yean no worries at all. 😄

**Comment by bastiW** [comment]
Any update on this? I also just upgraded my blog to next 13, makes totally sense :)

**Comment by timlrx** [comment]
I have incorporated most of the changes in v2 - https://github.com/timlrx/tailwind-nextjs-starter-blog/pull/658. Thanks for taking the first stab!

**Pull request closed without merging**
