### PR TITLE
fix: code block space #209

### PR DESCRIPTION
**Pull request by llovvoll**
Hi, 

I'm not sure if the pr solves #209 issue

### CODE REVIEW

**Comment by timlrx** [comment]
Works for the example in the issue but does not work for this one:
image

Instead of targeting `text-code-white` try targeting the last `span`?

**Comment by llovvoll** [comment]
> Works for the example in the issue but does not work for this one:
> image
> 
> Instead of targeting `text-code-white` try targeting the last `span`?

Sorry, I missed that point, I have updated the commit

**Comment by timlrx** [comment]
image

I think we have to handle the case where the last element is not wrapped in a span:

```
<div class="code-line">
<span class="text-code-blue">git</span>
 remote 
<span class="text-code-blue">add</span>
 template git@github.com:timlrx/tailwind-nextjs-starter-blog.git
</div>
```

**Comment by llovvoll** [comment]
Agree, It may take time to read remarkJS document

**Comment by renomureza** [comment]
Not all have span, example: https://tailwind-nextjs-starter-blog.vercel.app/blog/new-features-in-v1#configuring-a-blog-post-frontmatter

**Comment by llovvoll** [comment]
I think this pr can close first.

**Pull request closed without merging**
