### PR TITLE
Add Docker support

### LINKED ISSUE #1004: Add Dockerfile for deploy this service
**Is your feature request related to a problem? Please describe.**
It would be cool to have an example of a good Dockerfile to deploy this blog on your machine

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by eshut**
## Add Docker Support for Tailwind Next.js Starter Blog

This PR adds Docker support for the [Tailwind Next.js Starter Blog](https://github.com/timlrx/tailwind-nextjs-starter-blog), allowing users to easily run and deploy the blog in a containerized environment.

### Why This Change
After reviewing [Issue #1004](https://github.com/timlrx/tailwind-nextjs-starter-blog/issues/1004), I realized the current documentation lacked guidance on setting up Docker for this project. The solution provided by @timlrx didn’t fully address the issue, and I spent around 4 hours troubleshooting to understand and resolve it.

### Changes Made
- Added `Dockerfile` for building the Next.js blog

### Benefits
- Simplifies deployment and local setup for users familiar with Docker
- Ensures consistency across different environments

### Related Issue
Closes #1004

### Additional Notes
Let me know if there are any adjustments or additional documentation needed. I hope this contribution makes Docker support accessible and reduces troubleshooting time for others!

### CODE REVIEW

**Comment by eshut** [comment]
@timlrx Please also see #1047 as well

**Comment by timlrx** [comment]
I understand what you are trying to do, but I think my suggested approach of using the official example repo dockerfile results in a better production build with full feature parity and optimised image size. The current proposed solution only targets a static build.

If that's what you are looking for then glad to see it work! However, I would not suggest that as the default docker build. Perhaps I could add a README page for someone who is looking to deploy it via docker, without having to search through the issues or nextjs docs.

**Comment by eshut** [comment]
Yes @timlrx , thanks. That would be nice to have in README as an alternative

**Comment by timlrx** [comment]
Added over here - https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/main/faq/deploy-with-docker.md

**Pull request closed without merging**
