### PR TITLE
functionality for fixed navbar

### PR DESCRIPTION
**Pull request by atchox**
This provides functionality for a fixed navbar, which can be enabled by using the `stickyNav` key in the `siteMetadata.js` file. The CSS implementation of locking the scroll (by setting the overflow property on the body element) when the mobile nav is open has been replaced with the use of the npm package [`body-scroll-lock`](https://www.npmjs.com/package/body-scroll-lock). This allows for more consistent behavior across devices and prevents the page from scrolling to the top when the nav is closed.

https://github.com/user-attachments/assets/ed9042e7-cd93-43a0-b4b3-a6996b363631

### CODE REVIEW

**Comment by timlrx** [comment]
Thanks for the feature contribution, code looks fine to me but appreciate it if you could run it through prettier and push back the changes. I am getting the following errors on vercel:

```
10:21  Error: Replace `"flex·items-center·bg-white·dark:bg-gray-950·justify-between·py-10"` with `'flex·items-center·bg-white·dark:bg-gray-950·justify-between·py-10'`  prettier/prettier
11:30  Error: Insert `·`  prettier/prettier
12:20  Error: Replace `"·sticky·top-0"` with `'·sticky·top-0'`  prettier/prettier
```

**Comment by timlrx** [comment]
Hmm I get the following error in the console:
```
23-ee23754aea40848f.js:1 disableBodyScroll unsuccessful - targetElement must be provided when calling disableBodyScroll on IOS devices.
```

**Comment by atchox** [comment]
- the issue with the targetElement has been fixed. Some of the nav components are not unmounted when `navShow` is false.
- overflow functionality for the nav has been added. See the recordings as example (with placeholder links)
- padding has been adding to the mobile nav buttons for bigger tap area

https://github.com/user-attachments/assets/f2a736bf-6d95-47b2-a028-322229278814

https://github.com/user-attachments/assets/5c0160aa-0110-45db-8528-57220e11c98a

**Comment by timlrx** [comment]
I think we are almost there. There's a z-index issue with the code block and video element:
Screenshot 2024-08-11 at 12 42 46 PM

You can replicate it on the `/blog/release-of-tailwind-nextjs-starter-blog-v2.0` path. 

Otherwise, let's make `stickyNav` true by default and we can merge it in, thanks!

**Comment by atchox** [comment]
I couldn't recreate the issue with the video component but I fixed it for the code block. Hope this works!

**Comment by timlrx** [comment]
This works, thanks for the contribution!

**Pull request merged**
