### PR TITLE
Typescript

### PR DESCRIPTION
**Pull request by GautierArcin**
Hello,

I did some change for the typescript implementation, on the `lib` folder.

The MR might need a squash and merge ?

Kind regards,

Gautier

### CODE REVIEW

**Comment by frontendwizard** [comment]
Thanks for the time and the contribution. I like the typing on the `generate-rss` functions, but I'm not sure about manually typing the return type of each function. Can't we rely on type inference there? What do you think?

**Comment by timlrx** [comment]
Good with the changes as well. We can go with @frontendwizard suggestion. Squash and merge is fine after the merge conflict is resolved, thanks.

**Comment by GautierArcin** [comment]
Thank you. I applied the change from @frontendwizard. 

I also did a `git rebase`, to do a squash & merge, and resolve conflict.  Git still considers that `lib/generate-rss.ts` is a conflict, even though I did correct it during the rebase. I introduced two very minor conflicts on `.gitignore` (I don't know... Why git considers it a conflict ?) and `package.json` (on version string). 

What do you think @timlrx  ?

**Comment by timlrx** [comment]
You would need to merge the latest typescript branch to your branch, resolve the merge conflict locally, commit the changes and push it back. Perhaps you are not pulling in the updated branch from this repo? You might need to add this repo as a git remote and sync your fork with it.

**Comment by timlrx** [comment]
Let me know if you still have issues and I will resolve the conflict on your behalf but otherwise it's a good skill to pick up :)

**Comment by frontendwizard** [comment]
I can update the typescript branch with the latest commits from v1, the conflicts probably comes from there.

**Comment by frontendwizard** [comment]
I'm confused, I believe this branch is introducing changes from master. Do we want that?

**Comment by GautierArcin** [comment]
I did an hard reset from `origin/typescript`, applied the (original) changes manually and (force)-pushed them. Everything should be allright now.

I think both branch diverged during the rebase. I was also confused because the branch was considered 14 commit ahead, 20 commit behind origin, so I think it was the best to start once again from the clean branch.

**Comment by timlrx** [comment]
Great, I think it's good now, thanks! Proceeding to merge

**Pull request merged**
