### PR TITLE
V2

### PR DESCRIPTION
**Pull request by timlrx**
## Change Log

- New set up with next 13, app directory and React Server Components
- Typescript first
- Updated dependencies
- Contentlayer to manage most of the content logic
- Use next 13 metadata and SEO best practice
- Use pliny newsletter, comments, analytics, search and misc utils
- New search feature that supports local search with kbar and algolia
- Update `editUrl` to point to `main` instead of `master`
- Updated analytics config setup with more props exposed
    - Thanks to umami's free tier, you can now view the site's analytics over [here](https://analytics.umami.is/share/4HfD9TwtLgcTOkQr/Tailwind%20Nextjs%20Starter)!
- Styling updates:
    -  Updated tailwind typography to use tailwind 3 defaults and remove more boilerplate. Also updated default primary theme color and gray palette.
    - Switch Inter for Space Grotesk
    - New `PostBanner` layout for blog posts
    - New `ListLayoutWithTags` layout for blog post listings. Used the new layout in place of the previous `ListLayout` in the blog listings and tags routes.

### CODE REVIEW

**Comment by abhinavpatel0** [comment]
PS C:\Users\hp\Desktop\tailwind-nextjs-starter-blog-2> npm run build

> tailwind-nextjs-starter-blog@1.5.6 build
> cross-env INIT_CWD=$PWD next build && cross-env NODE_OPTIONS='--experimental-json-modules' node ./scripts/postbuild.mjs

Failed to compile.

file:///C:/Users/hp/Desktop/tailwind-nextjs-starter-blog-2/node_modules/@effect-ts/otel/_mjs/Processor/Simple/index.mjs:7
import { ConsoleSpanExporter, SimpleSpanProcessor } from "@opentelemetry/sdk-trace-base";
         ^^^^^^^^^^^^^^^^^^^
SyntaxError: Named export 'ConsoleSpanExporter' not found. The requested module '@opentelemetry/sdk-trace-base' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@opentelemetry/sdk-trace-base';
const { ConsoleSpanExporter, SimpleSpanProcessor } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:438:15)
    at async C:\Users\hp\Desktop\tailwind-nextjs-starter-blog-2\node_modules\next-contentlayer\dist\index-cjs.cjs:72:49

file:///C:/Users/hp/Desktop/tailwind-nextjs-starter-blog-2/node_modules/@effect-ts/otel/_mjs/Processor/Simple/index.mjs:7
import { ConsoleSpanExporter, SimpleSpanProcessor } from "@opentelemetry/sdk-trace-base";
         ^^^^^^^^^^^^^^^^^^^
SyntaxError: Named export 'ConsoleSpanExporter' not found. The requested module '@opentelemetry/sdk-trace-base' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@opentelemetry/sdk-trace-base';
const { ConsoleSpanExporter, SimpleSpanProcessor } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:438:15)
    at async C:\Users\hp\Desktop\tailwind-nextjs-starter-blog-2\node_modules\next-contentlayer\dist\index-cjs.cjs:72:49


> Build failed because of webpack errors

**Comment by timlrx** [comment]
> it took me about half day to migrate my site to this newest version.
> 
> there are some issues. I'd like to make a PR after this PR is merged

Thanks for testing it out. How about making a PR directly to this branch with the fixes? It's probably better than waiting for it to be merged into master as I am also patching things along the way.

**Comment by timlrx** [comment]
@ttys3 it was accurate when it was written in 2021 :). I will still retain it as it documents the changes between v0 and v1. There's going to be a new release blog post that mentions we are back to mdx with contentlayer in v2.

**Comment by 0x4slan** [comment]
Hi guys, when are you planning to release this new version?

**Comment by timlrx** [comment]
> Hi guys, when are you planning to release this new version?

A little busy over the past few days, will get it done over the weekends. There are no further changes that I wish to make other than writing up a blog post on the new features so definitely clone it and give it a try. Thanks!

**Pull request merged**
