### PR TITLE
fix: update comments component incase of no provider

### PR DESCRIPTION
**Pull request by talhatahir**
Incase if someone does not have any commenting platform enabled, the code will still show the Load Comments button.
This PR fixes it and only shows the Load Comments button if a commenting platform is provided.

### CODE REVIEW

**Comment by talhatahir** [comment]
@timlrx please be so kind to have a look at this PR.

**Comment by timlrx** [comment]
There's an error in the deployed build: 

```
Error: 
  x An object member cannot be declared optional
    ,-[/vercel/path0/components/Comments.tsx:11:1]
```

Could you fix it and ensure that it builds without error?

**Comment by talhatahir** [comment]
@timlrx Fixed it! Thanks ✌️

**Comment by timlrx** [comment]
Thanks for the fix!

**Pull request merged**
