### PR TITLE
V1

### PR DESCRIPTION
**Pull request by timlrx**

### CODE REVIEW

**Comment by DoctorDerek** [comment]
Nice job 👍

Any features or PRs I can help with?

**Comment by timlrx** [comment]
Thanks! this is just a preview build for now. Feature-wise, there's one more I am looking to implement which is to make it easier to customize the theme by switching the hardcoded `blue` color to a `primary` color. Beyond that, any PR on the docs side is always appreciated - both on the code as well as the actual docs (readme, update guide, v1 new features - if it is not clear enough).

**Comment by aloisdg** [comment]
Any chance of adding typescript?

**Comment by DoctorDerek** [comment]
@aloisdg I've discussed the idea of creating a TS fork of this project with @timlrx but this version is gonna stay JS

**Comment by timlrx** [comment]
These should be all the features and changes I plan to introduce in v1. Since @frontendwizard kindly volunteered to help maintain a typescript branch, we will include that in the v1 release. If you have problems migrating to v1 or think that the documentation requires more explanation in particular areas, feel free to raise them over here.

**Pull request merged**
